### ISSUE TITLE
请问流式输出的话该如何去写呢？

### ISSUE THREAD

**Issue by Summercuisine** [CaoYunzhou/poe-openai-proxy#1]
这样写是错的不能流式输出可否给个例子`url = 'http://127.0.0.1:8080/v1/chat/completions'
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer sk-123456'
}
data = {
    "model": "chinchilla",
    "messages": [{"role": "user", "content": "你好"}]
}

response = requests.post(url, headers=headers, data=json.dumps(data), stream=True)

for line in response.iter_lines():
    if line:
        json_response = json.loads(line)
        print(json_response['choices'][0]['text'])`

**Comment by CaoYunzhou** [comment]
post结构体，加上stream=true应该就可以

**Comment by CaoYunzhou** [comment]
一般流式输出都不是在程序上做，例如js或者nginx实现

**Comment by Summercuisine** [comment]
> post结构体，加上stream=true应该就可以
额我加上了啊问题返回还是一整句难道.py不行》？

**Comment by CaoYunzhou** [comment]
curl是不能流式输出的，stream流是需要buff缓冲区来实现的

**Comment by Summercuisine** [comment]
> 你可以找一个开源web项目对接，就是流式输出，至于python怎么实现流式输出，百度下

OKOK
