### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by cjw-666** [CaoYunzhou/poe-openai-proxy#10]
通过railway部署，提示404 page not found。
对接到前端程序之后也提示404 page not found

<img width="910" alt="截屏2023-07-25 15 15 38" src="https://github.com/CaoYunzhou/poe-openai-proxy/assets/39663688/9d6de214-f05e-4803-a509-fdd45180bb5f">

**Comment by CaoYunzhou** [comment]
fix by https://github.com/CaoYunzhou/poe-openai-proxy/pull/11
