### ISSUE TITLE
WebSocket connected问题

### ISSUE THREAD

**Issue by 848150331** [CaoYunzhou/poe-openai-proxy#12]
运行一段时间后，出现这个报错：client error: no available client，只能手动重启才行
![报错微信截图_20230726131108](https://github.com/CaoYunzhou/poe-openai-proxy/assets/49086826/e9a14d0d-1c3e-45a5-a6b3-3bbdb3d7fad3)

**Comment by CaoYunzhou** [comment]
ws的问题，这个目前没有好的解决办法，只能进行重试，客户端如果发送大量的ws,poe心跳会导致poe服务器承受巨大的网络开销

**Comment by 848150331** [comment]
大佬，可以加一个每隔一段时间发送一个post给3.5models让poe保持心跳吗，不知道这样能不能保持ws连接，或者检测错误自动重启啥的...

**Comment by 848150331** [comment]
> ws的问题，这个目前没有好的解决办法，只能进行重试，客户端如果大量发送ws，poe心跳会导致poe服务器承受巨大的网络开销

大佬，可以加一个每隔时间发个帖子给3.5models让poe保持心跳吗，不知道这样能不能保持ws一段连接，或者检测错误自动重启啥的...

**Comment by CaoYunzhou** [comment]
> > ws的问题，这个目前没有好的解决办法，只能进行重试，客户端如果大量发送ws，poe心跳会导致poe服务器承受巨大的网络开销
> 
> 大佬，可以加一个每隔时间发个帖子给3.5models让poe保持心跳吗，不知道这样能不能保持ws一段连接，或者检测错误自动重启啥的...

这个也不太现实，因为poe的网页限制了同一时刻只能有一个对话，这样做等于无限占用token的令牌时长，逆向工程是有很多限制的
