### ISSUE TITLE
这个不支持ChatGPT Next Web吗？

### ISSUE THREAD

**Issue by pizixi** [CaoYunzhou/poe-openai-proxy#13]
![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/56673215/ba7d63cb-8e9a-480d-b57b-2d107057efff)
![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/56673215/da950495-5820-4271-a915-7fefa401c1fe)

**Comment by CaoYunzhou** [comment]
401 你的auth header没配置

**Comment by pizixi** [comment]
配了

**Comment by CaoYunzhou** [comment]
> 配了

curl能返回就是正常的，chatnex-web我没怎么用过了，我用的是https://github.com/CaoYunzhou/chatbot-ui 目前没问题

**Comment by pizixi** [comment]
ChatGPT Next Web 有window客户端，可以试试

**Comment by imhut** [comment]
同样401
