### ISSUE TITLE
启动时报错，接口404 Not Found

### ISSUE THREAD

**Issue by lirui-ray** [CaoYunzhou/poe-openai-proxy#14]
![QQ截图20230726141651](https://github.com/CaoYunzhou/poe-openai-proxy/assets/82756879/45d55598-5cf1-4ca6-96d2-54209f98153d)
![QQ截图20230726141631](https://github.com/CaoYunzhou/poe-openai-proxy/assets/82756879/b1289db6-189a-45aa-895d-9579aeccebfb)
![QQ截图20230726142012](https://github.com/CaoYunzhou/poe-openai-proxy/assets/82756879/aee7717e-26e3-4262-a096-e421d116a04c)

**Comment by CaoYunzhou** [comment]
用最新docker镜像再试下

**Comment by lirui-ray** [comment]
docker搞定了，大佬有没有交流群或者联系方式有些其他问题求助

**Comment by CaoYunzhou** [comment]
> docker搞定了，大佬有没有交流群或者联系方式有些其他问题求助

我也不是非常懂，也在学习golang中
