### ISSUE TITLE
一顿操作猛如虎，结果404了，来自rainway一键安装

### ISSUE THREAD

**Issue by onlinedear** [CaoYunzhou/poe-openai-proxy#17]
部署日志
`2023/07/26 12:54:06 load proxy is
﻿2023/07/26 12:54:06 registering client: pPIZUjHuHUCPDgoqoCpclg%3D%3D, proxy
﻿2023/07/26 12:54:06 using proxy
﻿2023/07/26 12:54:06 registering client: 0gS8cz2Iyq0AdfUWOuOGlg%3D%3D, proxy
﻿2023/07/26 12:54:06 using proxy
﻿2023/07/26 12:54:06 new client 0gS8cz2Iyq0AdfUWOuOGlg%3D%3D , proxy <nil>
﻿2023/07/26 12:54:06 new client pPIZUjHuHUCPDgoqoCpclg%3D%3D , proxy <nil>
﻿2023/07/26 12:54:06 registering client: ScZBSvulmX7JliWGTS1Dsw%3D%3D, proxy
﻿2023/07/26 12:54:06 using proxy
﻿2023/07/26 12:54:06 new client ScZBSvulmX7JliWGTS1Dsw%3D%3D , proxy <nil>
﻿2023/07/26 12:54:12 Downloading channel data...
﻿2023/07/26 12:54:12 Downloading channel data...
﻿2023/07/26 12:54:12 Downloading channel data...
﻿2023/07/26 12:54:15 Subscribing to mutations
﻿2023/07/26 12:54:15 Subscribing to mutations
﻿2023/07/26 12:54:15 Subscribing to mutations
﻿2023/07/26 12:54:15 WebSocket connected.
﻿2023/07/26 12:54:16 WebSocket connected.
﻿2023/07/26 12:54:16 WebSocket connected.
﻿INFO: Success tokens: [0gS8cz2Iyq0AdfUWOuOGlg%3D%3D pPIZUjHuHUCPDgoqoCpclg%3D%3D ScZBSvulmX7JliWGTS1Dsw%3D%3D]
﻿ERROR: Error tokens: []
﻿[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
﻿[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
﻿- using env:	export GIN_MODE=release
﻿- using code:	gin.SetMode(gin.ReleaseMode)
﻿[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
﻿[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
﻿[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
﻿[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
﻿[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
﻿[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
﻿[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
﻿Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
﻿[GIN-debug] Listening and serving HTTP on :8080
﻿[GIN] 2023/07/26 - 12:54:53 | 404 |       1.137µs | 115.199.123.116 | GET      "/"
﻿[GIN] 2023/07/26 - 12:54:54 | 404 |         877ns | 115.199.123.116 | GET      "/"
﻿[GIN] 2023/07/26 - 12:56:10 | 404 |       1.347µs | 115.199.123.116 | GET      "/"`

**Comment by onlinedear** [comment]
构建日志
`=========================
﻿Using Detected Dockerfile
﻿=========================
﻿
﻿context: a14fb8cf5872470f89f2e496b9eef0ad
﻿#1 [internal] load build definition from Dockerfile
﻿#1 transferring dockerfile: 356B done
﻿ 
﻿#1 DONE 0.1s
﻿ 
﻿#2 [internal] load .dockerignore
﻿#2 transferring context: 2B done
﻿ 
﻿#2 DONE 0.2s
﻿ 
﻿#3 [internal] load metadata for docker.io/library/golang:1.20-alpine
﻿ 
﻿#3 DONE 0.3s
﻿ 
﻿#4 [internal] load metadata for docker.io/library/alpine:latest
﻿#4 DONE 0.3s
﻿ 
﻿ 
﻿#5 [builder 1/4] FROM docker.io/library/golang:1.20-alpine@sha256:7839c9f01b5502d7cb5198b2c032857023424470b3e31ae46a8261ffca72912a
﻿#5 DONE 0.0s
﻿ 
﻿#6 [stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1
﻿#6 DONE 0.0s
﻿ 
﻿#7 [internal] load build context
﻿ 
﻿#7 transferring context: 128.20kB done
﻿#7 DONE 0.1s
﻿ 
﻿#8 [builder 2/4] WORKDIR /app
﻿#8 CACHED
﻿ 
﻿#9 [builder 3/4] COPY . .
﻿ 
﻿#9 DONE 0.1s
﻿ 
﻿#10 [builder 4/4] RUN go build
﻿ 
﻿#10 0.426 go: downloading github.com/gin-gonic/gin v1.9.1
﻿#10 0.426 go: downloading github.com/joho/godotenv v1.5.1
﻿#10 0.429 go: downloading github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
﻿#10 0.448 go: downloading github.com/bogdanfinn/tls-client v1.3.12
﻿#10 0.448 go: downloading github.com/bogdanfinn/fhttp v0.5.23
﻿#10 0.448 go: downloading github.com/google/uuid v1.3.0
﻿#10 0.449 go: downloading github.com/zhangyunhao116/skipmap v0.10.1
﻿#10 0.452 go: downloading github.com/gorilla/websocket v1.5.0
﻿ 
﻿#10 0.646 go: downloading github.com/zhangyunhao116/fastrand v0.3.0
﻿#10 0.654 go: downloading golang.org/x/net v0.10.0
﻿#10 0.654 go: downloading github.com/bogdanfinn/utls v1.5.16
﻿#10 0.654 go: downloading github.com/tam7t/hpkp v0.0.0-20160821193359-2b70b4024ed5
﻿#10 0.672 go: downloading gopkg.in/yaml.v3 v3.0.1
﻿#10 0.672 go: downloading github.com/pelletier/go-toml/v2 v2.0.8
﻿#10 0.672 go: downloading github.com/mattn/go-isatty v0.0.19
﻿#10 0.672 go: downloading github.com/go-playground/validator/v10 v10.14.0
﻿#10 0.672 go: downloading google.golang.org/protobuf v1.30.0
﻿#10 0.672 go: downloading github.com/ugorji/go/codec v1.2.11
﻿#10 0.672 go: downloading github.com/gin-contrib/sse v0.1.0
﻿#10 0.709 go: downloading golang.org/x/sys v0.8.0
﻿ 
﻿#10 0.782 go: downloading golang.org/x/text v0.9.0
﻿#10 0.782 go: downloading github.com/gabriel-vasile/mimetype v1.4.2
﻿#10 0.782 go: downloading golang.org/x/crypto v0.9.0
﻿#10 0.782 go: downloading github.com/leodido/go-urn v1.2.4
﻿#10 0.782 go: downloading github.com/go-playground/universal-translator v0.18.1
﻿#10 0.790 go: downloading github.com/andybalholm/brotli v1.0.4
﻿ 
﻿#10 0.817 go: downloading github.com/go-playground/locales v0.14.1
﻿ 
﻿#10 0.853 go: downloading github.com/klauspost/compress v1.15.12
﻿ 
﻿#10 DONE 20.6s
﻿ 
﻿ 
﻿#11 [stage-1 2/3] WORKDIR /app
﻿#11 CACHED
﻿ 
﻿#12 [stage-1 3/3] COPY --from=builder /app/poe-openai-proxy .
﻿#12 DONE 0.1s
﻿ 
﻿ 
﻿#13 exporting to image
﻿#13 exporting layers 0.1s done
﻿ 
﻿#13 writing image sha256:728827d61e7750abf2275cb888bc4645eb585880691d1a6116b02942493ef7f1 done`

**Comment by CaoYunzhou** [comment]
这是逆向api，不是web项目

**Comment by onlinedear** [comment]
大神，是不是应该在项目下方写个配套教材，指引我们这些小白安装哪个web端，然后让我们部署的这个api网址用起来。谢谢

**Comment by onlinedear** [comment]
刚才我部署了chatgpt-ui 不知道哪里修改自己的网址 只是修改host地址报错 我又改回openai了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月26日 23:49 |
| 收件人 | CaoYunzhou/poe-openai-proxy ***@***.***> |
| 抄送人 | xiaoxin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [CaoYunzhou/poe-openai-proxy] 一顿操作猛如虎，结果404了，来自rainway一键安装 (Issue #17) |

大神，是不是应该在项目下方写个配套教材，指引我们这些小白安装哪个web端，然后让我们部署的这个api网址用起来。谢谢

#16
你可以用这些优秀的web项目，改一下域名和auth header就可以了，我用的是chatbot-ui这个项目

**Comment by CaoYunzhou** [comment]
其他的web项目部署基本上都写的很详细了，自己看README
