### ISSUE TITLE
如何解决并发问题？我想部署给公司的人用

### ISSUE THREAD

**Issue by ItManner** [CaoYunzhou/poe-openai-proxy#19]
用镜像程序调用本项目启动的API，发现只能一个并发

**Comment by CaoYunzhou** [comment]
配置N个poe-token，同一时刻一个poe-token只能用一个会话

**Comment by ItManner** [comment]
还有回复时间特别漫长，韩国CN2线路服务器，你的也是这样吗
![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/133472049/f59f90d6-5a02-484a-9f59-3bf695824d63)

**Comment by CaoYunzhou** [comment]
> 还有回复时间特别漫长，韩国CN2线路服务器，你的也是这样吗 ![image](https://user-images.githubusercontent.com/133472049/256414644-f59f90d6-5a02-484a-9f59-3bf695824d63.png)

user > you server  > poe > openai
gpt-4 本来就很慢

**Comment by CaoYunzhou** [comment]
![截图_选择区域_20230727112133](https://github.com/CaoYunzhou/poe-openai-proxy/assets/28099773/7a293f4d-b0b3-493f-abe8-448a3a672767)
我用railway的速度，目前能接受

**Comment by ItManner** [comment]
不对劲，红框内是我的程序发送的，下面那条是我在poe发送的，两次回答有区别
![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/133472049/00e1e43f-863b-4efc-82b2-ffadf5b94b66)
![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/133472049/0dcbfb48-a0d4-4d80-a03c-cfbb6f843db1)

**Comment by suidu-pro** [comment]
> 不对劲，红框内是我的程序发送的，下面那条是我在poe发送的，两次回答有区别 ![image](https://user-images.githubusercontent.com/133472049/256415434-00e1e43f-863b-4efc-82b2-ffadf5b94b66.png) ![image](https://user-images.githubusercontent.com/133472049/256415592-0dcbfb48-a0d4-4d80-a03c-cfbb6f843db1.png)

跟你同样问题，而且周卡也取消了，这个没法玩了

**Comment by CaoYunzhou** [comment]
惊讶。。。我测试看看

**Comment by jwdstef** [comment]
只能充月卡了啊

**Comment by CaoYunzhou** [comment]
我测试了下，这个有时候的回答像4.0有时候像3.5，很奇葩QAQ
