### ISSUE TITLE
panic: failed to download

### ISSUE THREAD

**Issue by Kot-nikot** [CaoYunzhou/poe-openai-proxy#2]
After the last update, the server is not stable. Sometimes it terminates with this error:
2023/07/21 16:07:48 request url is https://poe.com/api/receive_POST
2023/07/21 16:07:48 request url is https://poe.com/api/receive_POST
2023/07/21 16:07:48 request url is https://poe.com/api/receive_POST
2023/07/21 16:07:48 request url is https://poe.com/api/receive_POST
2023/07/21 16:07:49 request url is https://poe.com/api/receive_POST
2023/07/21 16:07:49 poeapi.go:281: Server returned a status code of 500 while downloading https://poe.com/api/receive_POST. Retrying (1/10)...
2023/07/21 16:07:50 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (2/10)...
2023/07/21 16:07:51 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (3/10)...
2023/07/21 16:07:52 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (4/10)...
2023/07/21 16:07:53 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (5/10)...
2023/07/21 16:07:54 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (6/10)...
2023/07/21 16:07:55 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (7/10)...
2023/07/21 16:07:56 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (8/10)...
2023/07/21 16:07:57 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (9/10)...
2023/07/21 16:07:58 poeapi.go:281: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (10/10)...
panic: failed to download https://poe.com/api/receive_POST too many times

goroutine 1189 [running]:
github.com/juzeon/poe-openai-proxy/poeapi.(*Client).sendQuery(0xc0000000c0, {0xa010ce, 0x4}, 0xe?, 0x0?)
        /home/ubuntu/poe-openai-proxy/poeapi/poeapi.go:604 +0x8d8
github.com/juzeon/poe-openai-proxy/poeapi.(*Client).sendRecv(0xc0000000c0, {0xc000a58340, 0xf}, {0xa0b544, 0x8}, {0xa0b544, 0x8}, 0x0?)
        /home/ubuntu/poe-openai-proxy/poeapi/poeapi.go:822 +0x77
created by github.com/juzeon/poe-openai-proxy/poeapi.(*Client).SendMessage
        /home/ubuntu/poe-openai-proxy/poeapi/poeapi.go:127 +0xa31

**Comment by CaoYunzhou** [comment]
poe token err, pls check token

**Comment by Kot-nikot** [comment]
I checked the tokens. All are up-to-date and work. This is also indicated by the absence of token errors.
poe-openai-proxy[84568]: INFO: Success tokens: 
poe-openai-proxy[84568]: ERROR: Error tokens: []

**Comment by Kot-nikot** [comment]
and also there is:
2023/07/21 18:07:23 [Recovery] 2023/07/21 - 18:07:23 panic recovered:
POST /v1/chat/completions HTTP/1.1
Host: XXXXXXXXXXXXXXXX:8000
Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: *
Connection: keep-alive
Content-Length: 3131
Content-Type: application/json
User-Agent: OpenAI/v1 PythonBindings/0.27.8
X-Openai-Client-User-Agent: {"bindings_version": "0.27.8", "httplib": "requests", "lang": "python", "lang_version": "3.10.6", "platform": "Linux-5.15.0-1038-oracle-aarch64-with-glibc2.35", "publisher": "openai", "uname": "Linux 5.15.0-1038-oracle #44-Ubuntu SMP Thu Jun 22 03:34:10 UTC 2023 aarch64"}


interface conversion: interface {} is nil, not string
/snap/go/current/src/runtime/iface.go:262 (0x40c369)
        panicdottypeE: panic(&TypeAssertionError{iface, have, want, ""})
/home/ubuntu/poe-openai-proxy/poeapi/utils.go:21 (0x9024cc)
        GetFinalResponse: return m["text"].(string)
/home/ubuntu/poe-openai-proxy/poe/poe.go:186 (0x902410)
        (*Client).Ask: Content: poeapi.GetFinalResponse(resp),
/home/ubuntu/poe-openai-proxy/router/router.go:160 (0x903caa)
        Ask: message, err := client.Ask(req.Messages, req.Model)
/home/ubuntu/poe-openai-proxy/router/router.go:65 (0x9049bc)
        Setup.func2: Ask(c, req, client)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c3da1)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x7c3d8c)
        CustomRecoveryWithWriter.func1: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c2ec6)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x7c2ea9)
        LoggerWithConfig.func1: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c1f2a)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x7c1bb1)
        (*Engine).handleHTTPRequest: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x7c185c)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/snap/go/current/src/net/http/server.go:2936 (0x64e955)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/snap/go/current/src/net/http/server.go:1995 (0x64b271)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/snap/go/current/src/runtime/asm_amd64.s:1598 (0x468bc0)
        goexit: BYTE    $0x90   // NOP

**Comment by CaoYunzhou** [comment]
> I checked the tokens. All are up-to-date and work. This is also indicated by the absence of token errors. poe-openai-proxy[84568]: INFO: Success tokens: poe-openai-proxy[84568]: ERROR: Error tokens: []

This indicates that you are not using the correct poe token, which must be obtained from the cookie of the official login account.

**Comment by Kot-nikot** [comment]
I am using a personal paid poe token which works fine in a web browser on a poe website. There are no problems with it. Therefore, I see this output in the log.

**Comment by Kot-nikot** [comment]
here is the server start log. Messages are sent and received. That error which I specified appears .

2023/07/22 03:55:35 load proxy is
2023/07/22 03:55:35 registering client: _METc1mssrSXXXXXXXXXX%3D%3D, proxy
2023/07/22 03:55:35 using proxy
2023/07/22 03:55:35 new client_METc1mssrSXXXXXXXXXX%3D%3D , proxy <nil>
2023/07/22 03:55:35 request url is https://poe.com
2023/07/22 03:55:36 Downloading channel data...
2023/07/22 03:55:36 request url is https://poe.com/api/settings
2023/07/22 03:55:36 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/Google-PaLM.json
2023/07/22 03:55:36 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/Assistant.json
2023/07/22 03:55:36 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/Claude-2-100k.json
2023/07/22 03:55:37 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/Claude-instant-100k.json
2023/07/22 03:55:37 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/GPT-4.json
2023/07/22 03:55:38 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/Claude-instant.json
2023/07/22 03:55:38 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/ChatGPT.json
2023/07/22 03:55:39 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/ChatGPT-16k.json
2023/07/22 03:55:39 request url is https://poe.com/_next/data/3xGPKwAzuxjlbHyxW1ErK/GPT-4-32k.json
2023/07/22 03:55:40 Subscribing to mutations
2023/07/22 03:55:40 request url is https://poe.com/api/gql_POST
2023/07/22 03:55:40 WebSocket connected.
INFO: Success tokens: [_METc1mssrSXXXXXXXXXX%3D%3D]
ERROR: Error tokens: []
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8000

**Comment by Kot-nikot** [comment]
I send a message and here is the error.

Ну ты сказочник
2023/07/22 04:04:19 request url is https://poe.com/api/gql_POST

2023/07/22 04:05:20 [Recovery] 2023/07/22 - 04:05:20 panic recovered:
POST /v1/chat/completions HTTP/1.1
Host: ltp-snxxxxxxxxxx.com:8000
Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: *
Connection: keep-alive
Content-Length: 4246
Content-Type: application/json
User-Agent: OpenAI/v1 PythonBindings/0.27.8
X-Openai-Client-User-Agent: {"bindings_version": "0.27.8", "httplib": "requests", "lang": "python", "lang_version": "3.10.6", "platform": "Linux-5.15.0-1038-oracle-aarch64-with-glibc2.35", "publisher": "openai", "uname": "Linux 5.15.0-1038-oracle #44-Ubuntu SMP Thu Jun 22 03:34:10 UTC 2023 aarch64"}


interface conversion: interface {} is nil, not string
/snap/go/current/src/runtime/iface.go:262 (0x40c369)
        panicdottypeE: panic(&TypeAssertionError{iface, have, want, ""})
/home/ubuntu/poe-openai-proxy/poeapi/utils.go:21 (0x9024cc)
        GetFinalResponse: return m["text"].(string)
/home/ubuntu/poe-openai-proxy/poe/poe.go:186 (0x902410)
        (*Client).Ask: Content: poeapi.GetFinalResponse(resp),
/home/ubuntu/poe-openai-proxy/router/router.go:160 (0x903caa)
        Ask: message, err := client.Ask(req.Messages, req.Model)
/home/ubuntu/poe-openai-proxy/router/router.go:65 (0x9049bc)
        Setup.func2: Ask(c, req, client)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c3da1)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x7c3d8c)
        CustomRecoveryWithWriter.func1: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c2ec6)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x7c2ea9)
        LoggerWithConfig.func1: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c1f2a)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x7c1bb1)
        (*Engine).handleHTTPRequest: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x7c185c)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/snap/go/current/src/net/http/server.go:2936 (0x64e955)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/snap/go/current/src/net/http/server.go:1995 (0x64b271)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/snap/go/current/src/runtime/asm_amd64.s:1598 (0x468bc0)
        goexit: BYTE    $0x90   // NOP

[GIN] 2023/07/22 - 04:05:20 | 500 |          1m0s | 141.144.205.230 | POST     "/v1/chat/completions"

**Comment by Kot-nikot** [comment]
At the same time, if I go to the website and open this dialog, then I see that my message has been sent and a response has been received. (Not knowing how to attach a screenshot here)

**Comment by CaoYunzhou** [comment]
> At the same time, if I go to the website and open this dialog, then I see that my message has been sent and a response has been received. (Not knowing how to attach a screenshot here)

Please don't change the port, and try to deploy with the latest docker image. At present, there is no problem in my test. Please also provide curl information.

**Comment by Kot-nikot** [comment]
I'm running the server not in docker

**Comment by CaoYunzhou** [comment]
my  test in latest docker image is working
```
2023/07/23 06:46:44 request url is https://poe.com/api/gql_POST
﻿2023/07/23 06:46:45 WebSocket connected.
﻿INFO: Success tokens: [rf03txxxxxxxxxLcaeaHgg%3D%3D]
﻿ERROR: Error tokens: []
﻿[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
﻿[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
﻿- using env:	export GIN_MODE=release
﻿- using code:	gin.SetMode(gin.ReleaseMode)
﻿[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
﻿[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
﻿[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
﻿[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
﻿[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
﻿[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
﻿[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
﻿Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
﻿[GIN-debug] Listening and serving HTTP on :8080
﻿[GIN] 2023/07/23 - 06:50:19 | 200 |     198.007µs |   104.198.9.185 | GET      "/v1/models"
﻿INFO: stream using client: rf03t7bHNDPb3TLcaeaHgg%3D%3D
﻿2023/07/23 06:50:37 bot name agouti
﻿DEBUG: Generated content to send: You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.
﻿2023/07/23 06:50:37 request url is https://poe.com/api/gql_POST
﻿请给我出一个脑筋急转弯题，内容要和“我爱冰激凌”有关。
﻿INFO: using model  gpt-3.5-turbo-16k
```

**Comment by CaoYunzhou** [comment]
pull code try test in your server

**Comment by Kot-nikot** [comment]
After the last edits of poe-api everything works.

**Comment by Kot-nikot** [comment]
After the last edits of poe-api everything works.
