### ISSUE TITLE
Server returned a status code of 403

### ISSUE THREAD

**Issue by Kot-nikot** [CaoYunzhou/poe-openai-proxy#20]
The page where you have implemented formkey generation requires a security check from CloudFlare. So you can't get it. We see an error in the log
Server returned a status code of 403 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=rf0xxxxxxxxxxxxcaeaHgg%3D%3D. Retrying (1/10)...

**Comment by jwdstef** [comment]
me too

**Comment by jwdstef** [comment]
2023/07/27 05:58:45 poeapi.go:284: Server returned a status code of 502 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=wRWOOFPn9PdKrhlhgjzLtg%3D%3D. Retrying (1/10)...
2023/07/27 05:58:46 poeapi.go:284: Server returned a status code of 502 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=wRWOOFPn9PdKrhlhgjzLtg%3D%3D. Retrying (2/10)...
2023/07/27 05:58:47 poeapi.go:284: Server returned a status code of 502 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=wRWOOFPn9PdKrhlhgjzLtg%3D%3D. Retrying (3/10)...
2023/07/27 05:58:49 poeapi.go:284: Server returned a status code of 502 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=wRWOOFPn9PdKrhlhgjzLtg%3D%3D. Retrying (4/10)...
2023/07/27 05:58:50 poeapi.go:284: Server returned a status code of 502 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=wRWOOFPn9PdKrhlhgjzLtg%3D%3D. Retrying (5/10)...
2023/07/27 05:58:51 poeapi.go:284: Server returned a status code of 502 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=wRWOOFPn9PdKrhlhgjzLtg%3D%3D. Retrying (6/10)...

**Comment by quantstu** [comment]
> me too

restart your docker container

**Comment by quantstu** [comment]
> The page where you have implemented formkey generation requires a security check from CloudFlare. So you can't get it. We see an error in the log Server returned a status code of 403 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=rf0xxxxxxxxxxxxcaeaHgg%3D%3D. Retrying (1/10)...

I found some abnormal requests. I banned the IP through WAF.

![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/100741190/43de0588-2144-4d56-9e3f-c97748cc51a5)

**Comment by Kot-nikot** [comment]
Here is what I get in return::
Response: OpenAI API error: Invalid response object from API: '"unauthorized"' (HTTP response code was 401)

**Comment by Kot-nikot** [comment]
> > Страница, на которой вы реализовали генерацию ключей формы, требует проверки безопасности от CloudFlare. Так что вы не можете получить его. Мы видим ошибку в журнале. Сервер вернул код состояния 403 при загрузке https://tsapi.liangctech.link/sdk/poe/formkey?pb=rf0xxxxxxxxxxxxcaeaHgg%3D%3D . Повторная попытка (1/10)...
> 
> Я нашел несколько ненормальных запросов. Я забанил IP через WAF.
> 
> ![изображение](https://user-images.githubusercontent.com/100741190/256443578-43de0588-2144-4d56-9e3f-c97748cc51a5.png)

In addition to the proxy server, I don’t have any requests for you. Only if I saw an error today and checked it in the browser. But this was already after the blocking.

**Comment by CaoYunzhou** [comment]
> > The page where you have implemented formkey generation requires a security check from CloudFlare. So you can't get it. We see an error in the log Server returned a status code of 403 while downloading https://tsapi.liangctech.link/sdk/poe/formkey?pb=rf0xxxxxxxxxxxxcaeaHgg%3D%3D. Retrying (1/10)...
> 
> I found some abnormal requests. I banned the IP through WAF.
> 
> ![image](https://user-images.githubusercontent.com/100741190/256443578-43de0588-2144-4d56-9e3f-c97748cc51a5.png)

![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/28099773/7b1e4dba-aec6-4fc8-bed2-3fdabf47f63e)
这个cf的429是不是限制的很严重啊？代码里面是携程去获取的，这个接口限制429会导致注册client不成功噢，有没有想法转成源代码？ @quantstu
