### ISSUE TITLE
panic recovered

### ISSUE THREAD

**Issue by Kot-nikot** [CaoYunzhou/poe-openai-proxy#21]
Today the following error appeared in the log:

runtime error: invalid memory address or nil pointer dereference
/snap/go/current/src/runtime/panic.go:260 (0x44ccfc)
        panicmem: panic(memoryError)
/snap/go/current/src/runtime/signal_unix.go:841 (0x44cccc)
        sigpanic: panicmem()
/home/ubuntu/poe-openai-proxy/poeapi/poeapi.go:76 (0x8f1e9e)
        (*Client).SendMessage: if name, ok := c.botNames[chatbot]; ok {
/home/ubuntu/poe-openai-proxy/poe/poe.go:162 (0x901c6b)
        (*Client).Ask: resp, err := c.client.SendMessage(bot, content, true, time.Duration(conf.Conf.Timeout)*time.Second)
/home/ubuntu/poe-openai-proxy/router/router.go:153 (0x9035ea)
        Ask: message, err := client.Ask(req.Messages, req.Model)
/home/ubuntu/poe-openai-proxy/router/router.go:58 (0x90427a)
        Setup.func2: Ask(c, req, client)
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/context.go:174 (0x7c3da1)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/recovery.go:102 (0x7c3d8c)
        CustomRecoveryWithWriter.func1: c.Next()
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/context.go:174 (0x7c2ec6)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/logger.go:240 (0x7c2ea9)
        LoggerWithConfig.func1: c.Next()
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/context.go:174 (0x7c1f2a)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/gin.go:620 (0x7c1bb1)
        (*Engine).handleHTTPRequest: c.Next()
/home/ubuntu/poe-openai-proxy/vendor/github.com/gin-gonic/gin/gin.go:576 (0x7c185c)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/snap/go/current/src/net/http/server.go:2936 (0x64e955)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/snap/go/current/src/net/http/server.go:1995 (0x64b271)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/snap/go/current/src/runtime/asm_amd64.s:1598 (0x468bc0)
        goexit: BYTE    $0x90   // NOP

Accordingly, on the device that sends the request:
HTTP code 500 from API ()

Before that everything worked fine

**Comment by CaoYunzhou** [comment]
the poe web upgrade ws , commiuty try fix it , QA: Pending issues are still being followed up [ws probe](https://github.com/ading2210/poe-api/pull/174)

**Comment by CaoYunzhou** [comment]
fix poe ws err, pls docker pull image deploy
