### ISSUE TITLE
请问可以添加Replit的一键部署嘛？

### ISSUE THREAD

**Issue by wintopic** [CaoYunzhou/poe-openai-proxy#28]
您好，请问Railway部署是否收费，如果可以请问能否提供下Replit的部署方式，谢谢！

**Comment by CaoYunzhou** [comment]
railway 或者 render等目前没收费，收费也就几十块一个月
replit的价格也是收费的US$0.40/day (Approximately US$12.80/month).
可以自行编译部署

**Comment by wintopic** [comment]
对不起，麻烦您了![image](https://github.com/CaoYunzhou/poe-openai-proxy/assets/97203022/0de2f33d-0cf6-429b-b138-38679e9b0ce5)
