### ISSUE TITLE
搭建成功但curl没反应

### ISSUE THREAD

**Issue by pzve** [CaoYunzhou/poe-openai-proxy#3]
按照教程搭建成功，但是curl没反应是空的，直接访问显示404，是什么原因呢大佬

**Comment by pzve** [comment]
![Uploading Screenshot_2023-07-23-00-13-15-803_com.sonelli.juicessh.jpg…]()

**Comment by pzve** [comment]
![Screenshot_2023-07-23-00-13-15-803_com sonelli juicessh](https://github.com/CaoYunzhou/poe-openai-proxy/assets/83093569/0f790f62-7f4d-4c18-9df6-77f244449c3f)

**Comment by CaoYunzhou** [comment]
最新版本看下，poe更新内容了
