### ISSUE TITLE
流式回复输出较慢

### ISSUE THREAD

**Issue by aabao325** [CaoYunzhou/poe-openai-proxy#5]
与juzeon/poe-openai-proxy比较而言，golang流式回复的内容输出较慢，不知是何原因导致的，希望可以优化，目前没有发现其他问题

**Comment by CaoYunzhou** [comment]
是一样的，这个跟你的容器服务部署在哪里，poe的响应速度和长度有关，放在HK目前不慢，这个跟openai的API的响应速度肯定不能比
