### ISSUE TITLE
panic recovered

### ISSUE THREAD

**Issue by Kot-nikot** [CaoYunzhou/poe-openai-proxy#5]
I have not been able to overcome this error. The server has been updated to the latest release. After some time, the server stops working. At the same time, in the terminal I see this:

Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: 2023/07/23 09:23:38 [Recovery] 2023/07/23 - 09:23:38 panic recovered:
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: POST /v1/chat/completions HTTP/1.1
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Host: ltp-snou.com:8000
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Accept: */*
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Accept-Encoding: gzip, deflate, br
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Authorization: *
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Connection: keep-alive
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Content-Length: 926
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: Content-Type: application/json
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: User-Agent: OpenAI/v1 PythonBindings/0.27.8
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: X-Openai-Client-User-Agent: {"bindings_version": "0.27.8", "httplib": "requests", "lang": "python", "lan>
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: interface conversion: interface {} is nil, not string
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /snap/go/current/src/runtime/iface.go:262 (0x40c369)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         panicdottypeE: panic(&TypeAssertionError{iface, have, want, ""})
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/poe-openai-proxy/poeapi/utils.go:21 (0x9024cc)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         GetFinalResponse: return m["text"].(string)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/poe-openai-proxy/poe/poe.go:186 (0x902410)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*Client).Ask: Content: poeapi.GetFinalResponse(resp),
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/poe-openai-proxy/router/router.go:160 (0x903caa)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         Ask: message, err := client.Ask(req.Messages, req.Model)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/poe-openai-proxy/router/router.go:65 (0x9049bc)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         Setup.func2: Ask(c, req, client)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c3da1)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*Context).Next: c.handlers[c.index](c)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x7c3d8c)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         CustomRecoveryWithWriter.func1: c.Next()
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c2ec6)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*Context).Next: c.handlers[c.index](c)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x7c2ea9)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         LoggerWithConfig.func1: c.Next()
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7c1f2a)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*Context).Next: c.handlers[c.index](c)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x7c1bb1)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*Engine).handleHTTPRequest: c.Next()
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x7c185c)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /snap/go/current/src/net/http/server.go:2936 (0x64e955)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /snap/go/current/src/net/http/server.go:1995 (0x64b271)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: /snap/go/current/src/runtime/asm_amd64.s:1598 (0x468bc0)
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:         goexit: BYTE        $0x90        // NOP
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]:
Jul 23 09:23:38 ltp-sellow poe-openai-proxy[10244]: [GIN] 2023/07/23 - 09:23:38 | 500 |          1m0s | 101.154.205.230 | POST     "/v1/chat/completions"

**Comment by CaoYunzhou** [comment]
close by  : https://github.com/ading2210/poe-api/issues/191
