### ISSUE TITLE
poe接口更改导致报错

### ISSUE THREAD

**Issue by ye4293** [CaoYunzhou/poe-openai-proxy#6]
poe在昨天下午又更新了接口，导致报错
![7e4ff3492b6cecaad13291eb0f90fda](https://github.com/CaoYunzhou/poe-openai-proxy/assets/137054651/a4ce826e-58f9-4c24-bdb5-50085de70fd1)

**Comment by xl-alt** [comment]
我也是

**Comment by xl-alt** [comment]
老哥解决了吗？

**Comment by CaoYunzhou** [comment]
close by  : https://github.com/ading2210/poe-api/issues/191
这猫抓老鼠太难受了，看poe-api是不是会一直封禁，如果一直封禁更新代码就变得没有意义了
