### ISSUE TITLE
全部都配置好了，最后一步启动报错。还忘大佬指点一下。

### ISSUE THREAD

**Issue by zichen-fujianwangluo** [CaoYunzhou/poe-openai-proxy#6]
报错详情
[root@VM-4-8-centos poe-openai-proxy-cn]# ./poe-openai-proxy
INFO: registering client: ["pCTDDKTKVnhQDNPnhqCz5Q%3D%3D"]
panic: invalid or missing token

goroutine 1 [running]:
github.com/lwydyby/poe-api.(*Client).getNextData(0xc000001ec0, 0x1)
        /root/go/pkg/mod/github.com/lwydyby/poe-api@v1.0.0/poe.go:363 +0x647
github.com/lwydyby/poe-api.(*Client).setupConnection(0xc000001ec0)
        /root/go/pkg/mod/github.com/lwydyby/poe-api@v1.0.0/poe.go:315 +0xce
github.com/lwydyby/poe-api.NewClient({0xc0003f7087, 0x20}, 0x0)
        /root/go/pkg/mod/github.com/lwydyby/poe-api@v1.0.0/poe.go:62 +0xef
github.com/juzeon/poe-openai-proxy/poe.NewClient({0xc0003f7087, 0x20})
        /www/poe-openai-proxy/poe/poe.go:36 +0xa5
github.com/juzeon/poe-openai-proxy/poe.Setup()
        /www/poe-openai-proxy/poe/poe.go:19 +0x65
main.main()
        /www/poe-openai-proxy/main.go:13 +0x25

**Comment by CaoYunzhou** [comment]
用容器一键启动吧，你的env需要 source .env

**Comment by zichen-fujianwangluo** [comment]
> 用容器一键启动吧，你的env需要 source .env

谢谢您的解答 找到问题了 是.env配置文件里的token=【】这个格式是不正确的 把【】去掉就行了 正确格式是TOKENS = "xxxxxx" 如果其他朋友遇到此问题去掉【】即可
