### ISSUE TITLE
使用docker部署出现错误

### ISSUE THREAD

**Issue by Miraitowa-wsy** [CaoYunzhou/poe-openai-proxy#7]
使用docker部署出现错误，这是错误的内容：
ERROR: Recovered in NewClient: %v
 runtime error: index out of range [1] with length 0
INFO: Success tokens: []
我使用compose部署，并按照要求填写了3个poe token，但是启动之后在日志中看到了这个

**Comment by CaoYunzhou** [comment]
https://github.com/ading2210/poe-api/commit/d840fbdb0c442c00da17064e98ede7ac31e140fd
这更新也太快了吧，1天几次更新。。。

**Comment by CaoYunzhou** [comment]
https://github.com/ading2210/poe-api/issues/188
无语中。

**Comment by Miraitowa-wsy** [comment]
是的更新太快了，不过刚刚我又重新拉取了镜像，但是又出现了新的问题：
`2023/07/24 03:30:06 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
2023/07/24 03:30:06 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
2023/07/24 03:30:07 Subscribing to mutations
2023/07/24 03:30:07 request url is https://poe.com/api/gql_POST 
2023/07/24 03:30:07 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
2023/07/24 03:30:07 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
2023/07/24 03:30:08 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
2023/07/24 03:30:08 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
2023/07/24 03:30:08 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
2023/07/24 03:30:09 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
2023/07/24 03:30:09 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
2023/07/24 03:30:10 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
2023/07/24 03:30:10 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
2023/07/24 03:30:11 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
2023/07/24 03:30:11 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
2023/07/24 03:30:12 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
2023/07/24 03:30:12 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
2023/07/24 03:30:12 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
2023/07/24 03:30:13 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
2023/07/24 03:30:13 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
2023/07/24 03:30:13 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
2023/07/24 03:30:14 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
2023/07/24 03:30:14 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
2023/07/24 03:30:14 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
2023/07/24 03:30:15 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
2023/07/24 03:30:15 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
2023/07/24 03:30:15 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
ERROR: Recovered in NewClient: %v
 failed to download https://poe.com/api/gql_POST too many times
2023/07/24 03:30:16 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
2023/07/24 03:30:16 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
2023/07/24 03:30:17 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
2023/07/24 03:30:18 poeapi.go:282: Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
ERROR: Recovered in NewClient: %v
 failed to download https://poe.com/api/gql_POST too many times
ERROR: Recovered in NewClient: %v
 failed to download https://poe.com/api/gql_POST too many times
INFO: Success tokens: []`

**Comment by CaoYunzhou** [comment]
> 

这个问题等上游那边的python修复了，我再跟进吧

**Comment by CaoYunzhou** [comment]
close by  : https://github.com/ading2210/poe-api/issues/191

**Comment by xl-alt** [comment]
> close by : [ading2210/poe-api#191](https://github.com/ading2210/poe-api/issues/191)

可以加下大佬的联系方式吗？有问题想请教一下

**Comment by CaoYunzhou** [comment]
> > close by : [ading2210/poe-api#191](https://github.com/ading2210/poe-api/issues/191)
> 
> 可以加下大佬的联系方式吗？有问题想请教一下

会golang可以PR
