### ISSUE TITLE
formkey解决方案

### ISSUE THREAD

**Issue by quantstu** [CaoYunzhou/poe-openai-proxy#9]
我通过逆向开发部署了一个可以自动获取poe-formkey以及poe-tag-id加密md5盐的api接口

- https://tsapi.liangctech.link/sdk/poe/formkey

经过我的测试，获取的key和salt可以完成请求，不知道对该项目是否有帮助

**Comment by CaoYunzhou** [comment]
可以提PR，我对cloudflare不太熟

**Comment by akl7777777** [comment]
> 我通过逆向开发部署了一个可以自动获取poe-formkey以及poe-tag-id加密md5盐的api接口
> 
> * https://tsapi.liangctech.link/sdk/poe/formkey
> 
> 经过我的测试，获取的key和salt可以完成请求，不知道对该项目是否有帮助

请问有入参吗,可以根据入参pb生成对应的formkey吗

**Comment by d1h1r1** [comment]
这个获取的token和key好像也是不对的

**Comment by akl7777777** [comment]
嗯,看起来好像不太对

**Comment by d1h1r1** [comment]
手动获取的keyform好像也用不了

**Comment by akl7777777** [comment]
手动获取的可以用啊

**Comment by akl7777777** [comment]
可能有时效性,可以考虑开个无头浏览器定时刷新存入数据库,然后轮询取用,我今天取的都能用

**Comment by quantstu** [comment]
> 请问有入参吗,可以根据入参pb生成对应的formkey吗

改了一下，支持传入pb参数获取，一个pb和对应一个key

- https://tsapi.liangctech.link/sdk/poe/formkey?pb=lX9dFOzQHrFYJAo9_uODew%3D%3D

你可以再尝试一下

**Comment by akl7777777** [comment]
> 

每次都一样吗,但是我在官网登录的时候,每次都是不一样的formkey

**Comment by CaoYunzhou** [comment]
fix by https://github.com/CaoYunzhou/poe-openai-proxy/pull/11
