### ISSUE TITLE
錯誤詢問

### ISSUE THREAD

**Issue by mmwong1984** [CaoYunzhou/poe-openai-proxy#9]
不知道是不是我的問題，我在某panel使用railway和docker mode都不行，實測其他的項目都是可以，就是出現錯誤，不能訪問。

错误：invalid status code: 502

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
INFO: registering client: 5Hz7ZpWOjcwszpKVzP2TIw%3D%3D
2023/07/15 15:09:00 Downloading channel data...
2023/07/15 15:09:03 Subscribing to mutations
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
INFO: registering client: 5Hz7ZpWOjcwszpKVzP2TIw%3D%3D
2023/07/15 15:10:35 Downloading channel data...
2023/07/15 15:10:38 Subscribing to mutations
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8999

確定有開端口

**Comment by CaoYunzhou** [comment]
提供更多的上下文，一般是没问题的，已经有几百人测试了这个项目了

**Comment by huanfeng123** [comment]
> 提供更多的上下文，一般是没问题的，已经有少数人测试过这个项目了

请问作者是否有联系方式呢 我需要完善一些功能 能联系您吗

**Comment by CaoYunzhou** [comment]
> > 提供更多的上下文，一般是没问题的，已经有少数人测试过这个项目了
> 
> 请问作者是否有联系方式呢 我需要完善一些功能 能联系您吗

可以自己PR
